spring:
  datasource:
    url: jdbc:postgresql://postgres-video-upload:5432/video_upload_db
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-api:8090}
